### PR TITLE
Getting ready for deployment

### LINKED ISSUE #215: Text/Edits for Multiple Regression and Consistency
I am uploading the current draft of the document I showed you this morning.  There are still a few things I need to add, but I wanted you to be able to get started.  I will upload a new version later and highlight what is new.

### PR DESCRIPTION
**Pull request by ethansaxenian**
- I've added all necessary texts and citations to Multiple Regression and OLS Estimators are Consistent. I believe we just need a sentence explaining the origin of the California Schools data for Multiple Regression.
- The 'motivated' members of the Control group now physically move into the Job Corps group in OLS Estimators are consistent. Two observations:
  1. To determine which people make the switch, I take 20% of the sample who have income above the median. This means that occasionally no people make the switch, for instance if all the members of the sample in the control group have income lower than the median.
  2. With small enough sample sizes, there may only be one two in the control group, meaning that sometimes all the control group members of the sample move to the Job Corps group, leaving none of the sample in the control group.
- The LLN simulation now goes until a sample size of 2000 (exactly the population size)

closes #215

### CODE REVIEW

**Comment by tbyker** [comment]
Can take your control sample in two parts.  20% from above the median (or even from 75th percentile) and all of these 20% get bumped over to Job Corps and the remaining 80% randomly from the control group.  We might also therefore require a minimum sample size of 10 in the violation examples?


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________
From: Ethan Saxenian ***@***.***>
Sent: Monday, August 23, 2021 12:50 PM
To: ProfessorAmanda/econsimulations ***@***.***>
Cc: Byker, Tanya S. ***@***.***>; Review requested ***@***.***>
Subject: [ProfessorAmanda/econsimulations] Getting ready for deployment (#217)


  *   I've added all necessary texts and citations to Multiple Regression and OLS Estimators are Consistent. I believe we just need a sentence explaining the origin of the California Schools data for Multiple Regression.
  *   The 'motivated' members of the Control group now physically move into the Job Corps group in OLS Estimators are consistent. Two observations:
     *   To determine which people make the switch, I take 20% of the sample who have income above the median. This means that occasionally no people make the switch, for instance if all the members of the sample in the control group have income lower than the median.
     *   With small enough sample sizes, there may only be one two in the control group, meaning that sometimes all the control group members of the sample move to the Job Corps group, leaving none of the sample in the control group.
  *   The LLN simulation now goes until a sample size of 2000 (exactly the population size)

closes #215<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fissues%2F215&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488484752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=V2n6eQ%2F1D%2BEBdxxzr4vNQGLGM%2Bl2aQSBOzwgM5T6osQ%3D&reserved=0>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ProfessorAmanda/econsimulations/pull/217<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F217&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488494749%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1FjtFDdxZWtF9HdmyUhJB17BSbSKEcTEACgBvqu%2FZ5c%3D&reserved=0>

Commit Summary

  *   increase sim length
  *   move protocol breakers to job corps group
  *   add texts
  *   add citation
  *   add citation
  *   adjust colors

File Changes

  *   M src/components/MultipleRegression/MultipleRegression.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F217%2Ffiles%23diff-a94eac0d1b72aa6252d44ef9698e86d16b2d229cc2da6428beb1d6567c69fe01&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488494749%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2F7J2aZGU%2B15jRDoB1ZoN5xEa6zr3S0FpGI4eVAhzmXI%3D&reserved=0> (8)
  *   M src/components/MultipleRegression/MultipleRegressionContainer.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F217%2Ffiles%23diff-3e29cc1be89bfbe93cfa6d9d5bf4b7194d1f9666ffc4acbfb90c3cf1931bb9b8&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488504736%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Zy009xWhaQwZ%2FyNMyOqyv18ZYvdspLnh0wSEVNl1M%2F8%3D&reserved=0> (2)
  *   M src/components/MultipleRegression/Scatter3D.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F217%2Ffiles%23diff-f388bd8e158f033527421268b441bccd8120be967bde6c1a2b559c17b302be6f&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488504736%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2hLEB%2FDqddfjiYnExr%2FQmzqKHkzgcJt7XmElmNMUKoE%3D&reserved=0> (1)
  *   M src/components/OLSEstimatorsAreConsistent/OLSEstimatorsAreConsistent.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F217%2Ffiles%23diff-2430ffc1b259ded817dd349a6ee39a9ac8a547c0d53ab5d02db847e4ab70dc9c&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488514730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mLqtK9X53nsZTcMesPS0NF1q4W5M1dvSWzBOkcTuA0s%3D&reserved=0> (25)
  *   M src/components/OLSEstimatorsAreConsistent/OLSEstimatorsAreConsistentContainer.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F217%2Ffiles%23diff-b1939872df762d530ea3e1c531149220fdbaf08073b0525028940f0d40d373e1&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488514730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kH%2BF1KcOgD2DyZkrYnAniIAPnrzXlRWdPmdmwtWkJtY%3D&reserved=0> (19)
  *   M src/components/OLSEstimatorsAreConsistent/PopulationPlot.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F217%2Ffiles%23diff-bb0fb539dab2c7c0177256b8b86f152c35bea581098f84c2d86ae75a15079d44&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488514730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jwydVGviRYj6HzE%2BBpd1IAlwPchzr2TBzT8UgX%2B8NCc%3D&reserved=0> (10)
  *   M src/components/OLSEstimatorsAreConsistent/SampleInput.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F217%2Ffiles%23diff-3987abc42b7920fd35bb0ecea40db4797d17c9497b9fe3213d26832783fda89b&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488524726%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2Yg41VF1NkaL7RP2aw1%2FxCg%2BMX7DIhV1ftq37j2kHlQ%3D&reserved=0> (2)
  *   M src/components/OLSEstimatorsAreConsistent/SamplePlot.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F217%2Ffiles%23diff-727d6749162d3f02d0301e59b46fd27e1ab16160fa8ac80444b39fff72fc38a0&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488524726%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nHWCVo6gUVZnvnWT72Df%2FftmbvZzEuYEsdwQ3w0M6L4%3D&reserved=0> (10)
  *   M src/components/SimulateSamples.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F217%2Ffiles%23diff-81ebe5e81f7ca1cd5378a5930a3f2f1d0bb3055465ff841337129568ec30f6b6&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488534728%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XnUcrXEHNUmHSuyz5fj%2BguxGtFI2AApdQumtQm35%2B9E%3D&reserved=0> (17)
  *   M src/lib/constants.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F217%2Ffiles%23diff-4948e93b6ff32fd5b5228f82edaceb099d7c5437eae914fe3448126e2ae075d3&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488534728%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Q9DfyTTbii7h3rqIcmCBcDf25kvYvAxbVBZDbsHkymk%3D&reserved=0> (26)

Patch Links:

  *   https://github.com/ProfessorAmanda/econsimulations/pull/217.patch<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F217.patch&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488544717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BBWw3lRYoAufwSbuOsGPvn3vMXwovmfpAC8KQ0cgjMg%3D&reserved=0>
  *   https://github.com/ProfessorAmanda/econsimulations/pull/217.diff<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F217.diff&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488544717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tjok3uRwKDico5mbukHCuzxooFnPXxV9%2FYXF4DE2PA4%3D&reserved=0>

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F217&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488554714%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Y2%2FEOwYyNkYdJs5MCEAkikw3kAFClk7mz%2Bx8tvLIZgk%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAP65VZ67D6JIPPUKH5KELPDT6J36PANCNFSM5CU7FRJA&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488554714%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jEl4pm7%2FL49vrJFhdg5ifvDZIDfp3FBU9WswexwI9vg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488564705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=adMlM%2BjuEhUKg%2BCdhiqlwWsifpqA96F8Uey%2Be%2B9KPro%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Ctbyker%40middlebury.edu%7Cc2e4b182b6944df7891908d966562861%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637653342488564705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8gkL9nNcpy4Y3BjxA%2FCihqlUUS7IhonrIp8CRJLrjX4%3D&reserved=0>.

**Comment by ProfessorAmanda** [comment]
Having LLN go all the way to 2000 is pretty cool! 

The rest looks like good progress.

**Comment by tbyker** [comment]
nevermind.  It's back.....


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by tbyker** [comment]
ok.  well, I may still need help.  because even with npm install, I don't see any updates when I git pull and then npm start.


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ProfessorAmanda** [comment]
Make sure you are on the branch called "updates." (git checkout updates)

Amanda G. Gregg
Assistant Professor of Economics, Middlebury College
Join My Personal Zoom Room<https://middlebury.zoom.us/my/agregg?pwd=OWlGMmZMSWJaUkowRG5DUWJtRm9CQT09> (Password: EconHist)
Office: Farrell House 101
Office Phone: (802) 443 - 3419
Pronouns: she/her/hers

________________________________

**Comment by tbyker** [comment]
ah


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
> Can take your control sample in two parts. 20% from above the median (or even from 75th percentile) and all of these 20% get bumped over to Job Corps and the remaining 80% randomly from the control group. We might also therefore require a minimum sample size of 10 in the violation examples?

Wouldn't this introduce non-random sampling? I think a better solution is to just use the highest 20% of the sample, regardless of the median. Alternatively, we could simply have some samples where no-one switches groups, which is probably more realistic but maybe less helpful from a teaching perspective.

I've been eating lunch so I missed your message about hopping on zoom. Have you figured it out yet?

**Comment by tbyker** [comment]
yes, that is true.  I guess it is a tradeoff between it "looking right" and being "completely right" and you are probably correctly that the latter is more important?!  Does is help to insist on a sample of at least 10?  Let's see what the simulation looks like.

yes, I got it figured out.  I was on the wrong branch


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
> yes, that is true.  I guess it is a tradeoff between it "looking right" and being "completely right" and you are probably correctly that the latter is more important?!  Does is help to insist on a sample of at least 10?  Let's see what the simulation looks like.

Even with a sample size of 10 this happens occasionally: 

Screen Shot 2021-08-23 at 1 45 37 PM

**Comment by tbyker** [comment]
Maybe it is getting too fussy, but, could you have a little message that pops up and says "given this random sample, none of those failing to follow the protocol were selected" in cases when this occurs.  It definitely still shows up in the simulation, so that is fine.

Thoughts?


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by tbyker** [comment]
Also, shouldn't the beta_0 be biased by this too if high earning control group folks and entering the treatment group?


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
> Also, shouldn't the beta_0 be biased by this too if high earning control group folks and entering the treatment group? 

It looks like it is to me

**Comment by ethansaxenian** [comment]
@tbyker, do you have some text explaining the California Schools data?

**Comment by tbyker** [comment]
not at this exact minute, sorry.  Heading out the door to a meeting


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Pull request merged**
