### PR TITLE
Preliminary Hypothesis Testing Simulation

### PR DESCRIPTION
**Pull request by ethansaxenian**
I've implemented the basics of the Hypothesis Testing simulation, which allows the user to simulate many samples and plots the means under a bell curve, coloring each point depending on whether or not the hypothesis test rejects or fails to reject the null hypothesis.

I believe all the math is correct but I am not familiar enough with hypothesis testing to be sure if the visualization is correct or not. @ProfessorAmanda and @tbyker let me know if this looks right! (`git checkout HT-sim`)

### CODE REVIEW

**Review by DavidGmidd — APPROVED** [review]

**Comment by tbyker** [comment]
Ethan, any chance you are at Shannon St and can help me get this running locally? So that I can take a look?

**Review by ProfessorAmanda — COMMENTED** [review]
Great progress! This gets the idea of what we wanted. Here are some comments:
1. I tried out a one-sided test (Ha: mu > mu_0), and I saw that there were red dots to the left of the population mean. With a one-sided test, there is no value to the left of the mean that would lead you to reject the null. So, make sure that p-values (or whatever rule you are using) is coded correctly for each kind of test. 
2. It would be nice for the user to be able to plot a couple means one at a time before embarking on the simulation.
3. We need some text at the beginning to introduce what is going on (something more than simulating type i error). Something like: "Now we simulation Type I error. In other words, if the true mean were actually [hypothesized mean], how often would we (incorrectly) reject the null hypothesis?"

Good hunting! This is shaping up great!

**Comment by ethansaxenian** [comment]
I just pushed some more changes:

Tanya and I met this afternoon and decided that it might be a good idea to have the right graph plot the standard normal curve and the test statistics for the samples. I've implemented this, let me know what you think (it is easy to switch back to plotting the actual means).

I added a button to sample once, let me know what you think of its placement (I'm not sure I even like it, just experimenting over here!)

Tanya and I also noticed the one-sided test problem. It seems like this might be a problem with the jStat functions we are using. I will look into this and perhaps we can discuss more when we meet tomorrow.

**Comment by ProfessorAmanda** [comment]
Thanks!

I'd rather have the actual means plotted, to save a level of abstraction. It might make sense to have a "standardize" button, similar to what we have for the CLT simulations.

I went to take a look at the single sample button, but got an error when I clicked the "simulate" button this time. Screen shot attached!

Yeah let's try to figure out what jstat is giving us.

Thanks again for helping us out so quickly yesterday. The presentation went over very well, and we got a lot of exposure.

Amanda G. Gregg
Assistant Professor of Economics, Middlebury College
Join My Personal Zoom Room<https://middlebury.zoom.us/my/agregg?pwd=OWlGMmZMSWJaUkowRG5DUWJtRm9CQT09> (Password: EconHist)
Office: Farrell House 101
Office Phone: (802) 443 - 3419
Pronouns: she/her/hers

________________________________

**Comment by ethansaxenian** [comment]
Could you post the screenshot again? I don't see it here.

**Comment by ethansaxenian** [comment]
@ProfessorAmanda, @tbyker the normal curve should now adjust based on the sample size! Let me know how it looks/feels and if you want me to make any changes.

Of note I have not yet fixed the one-sided test error.

**Comment by ethansaxenian** [comment]
The one-sided test error should now be fixed!

**Comment by ethansaxenian** [comment]
Although this now looks wrong (one sample, uniform, t-distribution):

Screen Shot 2021-07-01 at 3 37 22 PM

**Comment by tbyker** [comment]
Not that it would fix what is "wrong" -- presumably, you are referring to both red and green dots in the same region -- it would be helpful to include a vertical line at the "critical" mean for the relevant alpha value.


**********************************************
Tanya Byker

Assistant Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
> Not that it would fix what is "wrong" -- presumably, you are referring to both red and green dots in the same region -- it would be helpful to include a vertical line at the "critical" mean for the relevant alpha value. 

That is calculated using a z/t-table, correct?

**Comment by tbyker** [comment]
LOL, if you were using the z-score method, yes.  But yes, you can get it there and then "UN"-scale it to get the relevant mean -- 1) multiply by sd(Y_bar)  (ie sd(Y)/sqrt(n)), and 2) add back Mu_0.  Sound right, Amanda?  Remember if you are doing a t-sided test, there will be two vertical lines.


**********************************************
Tanya Byker

Assistant Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
> 1) multiply by sd(Y_bar)  (ie sd(Y)/sqrt(n))

What is Y_bar?


In regards to the overlap of red and green points:

In theory, couldn't we take two samples with the same mean but different standard deviations, such that we reject the null hypothesis for one and fail to reject for the other?

**Comment by tbyker** [comment]
Y_bar is the sample mean.

I am just reversing the calculation of the z-stat.  What is the equation you are using to calculate it?

On your second point, ah ... ok.  But in the simulation , you shouldn't see red and green dots in the same area, right?  It is just in the preliminary "playing" around period when you are changing things.  We might want to think of clearing out once you change things as it might be confusing to see green vs red dots past a certain point, but we can talk about that.


**********************************************
Tanya Byker

Assistant Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
>  I am just reversing the calculation of the z-stat. What is the equation you are using to calculate it? 

This is where we were using the `jStat` function.

> On your second point, ah ... ok. But in the simulation , you shouldn't see red and green dots in the same area, right? It is just in the preliminary "playing" around period when you are changing things. We might want to think of clearing out once you change things as it might be confusing to see green vs red dots past a certain point, but we can talk about that. 

Nothing was changed here, I just took 1,000 samples with the same sample size (10), using a t-distribution, and got the overlap.

**Comment by ProfessorAmanda** [comment]
Hi everybody,

I just took a look, and I did not see the overlap issue (maybe you fixed it already, Ethan)? More pressing is that the rejection region is on the wrong side, i.e. for a test with Ha: mu > mu_0, the red dots were on the left, where they should be on the right. And vice versa for Ha: mu < mu_0. So I think you just have that backwards. But other than that, it looks great to me! 

Whenever you're ready, I have smaller comments as well. But dang, you've basically got it.

**Comment by ethansaxenian** [comment]
The overlap issue only seems to occur with a t-distribution.

Good catch with the rejection region, looks like I mixed up H<sub>a</sub> and H<sub>0</sub>.

What are the smaller comments that you have?

**Comment by ProfessorAmanda** [comment]
Ah, okay, I'll take a look at the t graph.

I will make a new issue for the smaller comments.

**Comment by ethansaxenian** [comment]
What do you mean by "bins"?

**Comment by ProfessorAmanda** [comment]
Ah, sorry, yeah, let me explain. When you plot the dot plot, the dots are stacked according to some range of values, otherwise you'd just have one horizontal line of unique values. So I think what is happening is that dots within a range of values, some of which would lead to rejecting Ho and others that would not, are being stacked in the same column.

**Comment by ethansaxenian** [comment]
So the dots are only stacked if multiple samples have the same sample mean. I could see how two samples with the same mean could have two different standard deviations and thus one would be rejected and the other accepted. Is this what you mean?

**Comment by ProfessorAmanda** [comment]
That's not exactly what I meant, but actually I think what you said is right. In the case of the t-distribution, it's totally reasonable for two means to have different t scores if they have different sample standard deviations. We've cracked the case! The overlap is probably correct, in fact. 

But this is a further reason it might be nice to have a "standardize" button to show the distribution by t scores. I'm going to add that to my list of comments I just made in the new issue.

**Comment by ethansaxenian** [comment]
Hooray! I think this might be done after I push the most recent changes!

**Review by DavidGmidd — APPROVED** [review]

**Comment by tbyker** [comment]
Ethan, I still need help getting things to run locally.  Sorry.  If you want me to check this out, can you stop by?

**Review by DavidGmidd — APPROVED** [review]

**Pull request merged**
