### PR TITLE
Started new module

### PR DESCRIPTION
**Pull request by ethansaxenian**
I've mocked up a first draft of the new module based on the sketch we went over yesterday.

### CODE REVIEW

**Comment by ProfessorAmanda** [comment]
Hi Ethan, where can we find it? On the master branch?

**Comment by ethansaxenian** [comment]
the branch is called `new-module`.

(you can see this at the top of the page)

Screen Shot 2021-07-02 at 3 32 30 PM

**Comment by ProfessorAmanda** [comment]
Awesome!! Looking now...

**Comment by ProfessorAmanda** [comment]
Whoooooaaaa. 

Quite a first draft! It looks like it's working great. Next week, something you guys can consider it how to drive home that each point on the simulation graph represents a slope.

**Review by DavidGmidd — APPROVED** [review]

**Pull request merged**
