### PR TITLE
Fix conclusion

### PR DESCRIPTION
**Pull request by ethansaxenian**
I've fixed the hypothesis test conclusion according to the logic we went over today, however we only talked about the one-sample case. How does this change for a two-sample test? Does the true mean become the mean of population 1 and mu_0 becomes the mean of population 2?

### CODE REVIEW

**Comment by ProfessorAmanda** [comment]
Oh right, good call!

Because this gets confusing, here is the whole tree.

1. If Ha: mu_1 - mu_2 < 0 ("the cows produce more than before")
Reject Ho if mu_2 > mu_1
Fail to reject Ho if mu_2 <= mu_1

2. If Ha: mu_1 - mu_2 > 0 
Reject Ho if mu_2 < mu_1
Fail to reject Ho if mu_2 >= mu_1

3. If Ha: mu_1 - mu_2 != 0
Reject Ho if mu_2 != mu_1
Fail to reject if mu_2 = mu_1

**Comment by ethansaxenian** [comment]
> Oh right, good call!
> 
> Because this gets confusing, here is the whole tree.
> 
> 1. If Ha: mu_1 - mu_2 < 0 ("the cows produce more than before")
>    Reject Ho if mu_2 > mu_1
>    Fail to reject Ho if mu_2 <= mu_1
> 2. If Ha: mu_1 - mu_2 > 0
>    Reject Ho if mu_2 < mu_1
>    Fail to reject Ho if mu_2 >= mu_1
> 3. If Ha: mu_1 - mu_2 != 0
>    Reject Ho if mu_2 != mu_1
>    Fail to reject if mu_2 = mu_1

If Ha = mu_1 - mu_2 < 0, wouldn't we fail to reject if mu_2 > mu_1, because then the difference _is_ less than 0? Isn't the alternative hypothesis correct in this case?

**Comment by ethansaxenian** [comment]
Ok it should be complete now! Let me know how it looks and if I should merge to master.

**Comment by ProfessorAmanda** [comment]
Looks like it's working! Can I suggest a small change in the wording of the conclusion statement? (It's much better than it was, btw). "The true mean is....Therefore, we should... . Our conclusion above was correct." (I'm breaking up the second sentence and getting rid of the second therefore.)

**Comment by ethansaxenian** [comment]
I agree. Fixed!

**Comment by ProfessorAmanda** [comment]
Looks good! Let's merge to master and get ready for deployment (woot!)

**Pull request merged**
