### PR TITLE
Updating based on recent changes

### PR DESCRIPTION
**Pull request by ProfessorAmanda**

### CODE REVIEW

**Comment by waynew99** [comment]
Working on fixing it...

**Comment by ProfessorAmanda** [comment]
Thanks, bud! Is this one issue that keeps arising during the deployment step, or something different each time? It would be great to have this solved so I can fix small things after we lose you on Friday.

Amanda G. Gregg
Associate Professor of Economics, Middlebury College
Join My Personal Zoom Room<https://middlebury.zoom.us/my/agregg?pwd=OWlGMmZMSWJaUkowRG5DUWJtRm9CQT09> (Password: EconHist)
Office: Farrell House 101
Office Phone: (802) 443 - 3419
Pronouns: she/her/hers

________________________________

**Comment by waynew99** [comment]
I think the issue is pretty stand-alone. It's an issue about tests not able to run with service worker added.
I didn't find a quick fix to properly setup tests with service workers. For now, I'm skipping the tests on modules that involve service worker, so that we can deploy. I will keep investigating how to properly make tests work with Workers.

**Comment by ProfessorAmanda** [comment]
Cool!

Amanda G. Gregg
Associate Professor of Economics, Middlebury College
Join My Personal Zoom Room<https://middlebury.zoom.us/my/agregg?pwd=OWlGMmZMSWJaUkowRG5DUWJtRm9CQT09> (Password: EconHist)
Office: Farrell House 101
Office Phone: (802) 443 - 3419
Pronouns: she/her/hers

________________________________

**Comment by ProfessorAmanda** [comment]
So everything seems to be working now. This is maybe a silly question but did you mention that you were going to update the icon I see in the Chrome tab for the page? I still see a black triangle. I feel like I probably misunderstood what you meant.

Amanda G. Gregg
Associate Professor of Economics, Middlebury College
Join My Personal Zoom Room<https://middlebury.zoom.us/my/agregg?pwd=OWlGMmZMSWJaUkowRG5DUWJtRm9CQT09> (Password: EconHist)
Office: Farrell House 101
Office Phone: (802) 443 - 3419
Pronouns: she/her/hers

________________________________

**Comment by waynew99** [comment]
That's exactly what I intended to fix! The logo is showing up on my chrome. It is possibly be due to cached data in your browser. You can try holding down "Shift" and click the refersh button to force a full refresh.

**Comment by ProfessorAmanda** [comment]
Bingo! The full refresh worked. Cool!!

Amanda G. Gregg
Associate Professor of Economics, Middlebury College
Join My Personal Zoom Room<https://middlebury.zoom.us/my/agregg?pwd=OWlGMmZMSWJaUkowRG5DUWJtRm9CQT09> (Password: EconHist)
Office: Farrell House 101
Office Phone: (802) 443 - 3419
Pronouns: she/her/hers

________________________________

**Pull request merged**
