### PR TITLE
Violation 'animations'

### LINKED ISSUE #181: Violation(s) as an Animation
Moving this to a new issue for organization's sake:

>Feel free to tell me the following idea is dumb and/or too hard to implement:  Could we show the violation(s) as an animation?
>
>eg.  We highlight the observations that are going to violate protocol in their pre-violation position and then click to show their new spot on the scatter.  Kind of like a "toggle" the problem on and off.  This would be in the initial "take samples" and "play with things" part of the module.  Then you just tell the user this is what is happening with each sample in the simulation.  I think it is powerful to see why the problem is occurring.  This idea could be for the failure to follow protocol and outlier example.  I think it is visually obvious what is going on with the non-random sample.

If I am understanding this correctly, I think it would be doable in theory, but probably pretty complicated.

### PR DESCRIPTION
**Pull request by ethansaxenian**
This ended up being more straightforward than I expected. Just need some text to explain what's happening!

One question: do we want to be able to toggle the violation in the sample plot as well? This way we could see the difference in the best fit line before and after the violation. But that might get confusing with the data table. Perhaps we should display the before and after slope/intercept in the table?

closes #181

### CODE REVIEW

**Comment by ProfessorAmanda** [comment]
Yeah not bad! You are totally right that we need to make a decision about how to arrange the rest of the module after they toggle the violation. It might interesting to let them see the result with and without the violation. I also think we need to make the toggle violation more prominent, so that the user doesn't miss it. I think we're going to have to discuss when we meet tomorrow.

**Comment by ProfessorAmanda** [comment]
Do we think that the violations should be toggled ON by default?

**Comment by ethansaxenian** [comment]
A few changes:
- I've added some brief text describing the violation. This can probably be edited/improved
- the text is placed below the population plot, this looked better to me than placing it to the right or left
- The violations are now ON by default
- one switch controls both the population plot and the sample plot

**Comment by ProfessorAmanda** [comment]
Hey this looks pretty good! I like showing the text in a menacing RED BOX to show that an assumption has been violated, ha ha.

Can we make the toggle switch more clearly show when the violation is ON vs. OFF?

**Comment by ethansaxenian** [comment]
> Can we make the toggle switch more clearly show when the violation is ON vs. OFF?

How does it look now?

**Comment by ProfessorAmanda** [comment]
I think it'll be clearer if we change the word "Toggle" to "Turn," so it's clear what the action is. But otherwise this looks good!

**Comment by ProfessorAmanda** [comment]
Yeah looks good! We'll pick back up on Monday to make small changes to the wording, etc.

**Pull request merged**
