### PR TITLE
Violate assumptions

### LINKED ISSUE #173: Violate some assumptions
> Idea: what does it look like if we violate one of the assumptions?
→Take a non-random sample from the population. Eg. More likely to sample people in the treated group (bump up probability of sampling from that group). We will see that the estimator will converge to a value above the true value.
→ large outlier idea

### PR DESCRIPTION
**Pull request by ethansaxenian**
Added a non-random sampling option: 80% of the sample is random and the remaining 20% are exclusively from the Job Corps data.

Added a 'Human Error' option: When a sample is drawn, 20% of these data points are chosen randomly and multiplied by 10.

Let me know if this is what you had in mind. I can see some slight differences in the simulation, but nothing major, which makes me think I may have done something wrong.

closes #173

### CODE REVIEW

**Comment by tbyker** [comment]
I will look now.  We may need to increase the percentages.

Regarding the "human error," we want all of the errors to be applied to the control group.  If the error is randomly assigned it won't affect the consistency

**Comment by tbyker** [comment]
I am getting a "violate-assumptions did not match any files known to git" error

**Comment by ethansaxenian** [comment]
> I am getting a "violate-assumptions did not match any files known to git" error

Try 
```
git fetch
git checkout ...
```

**Comment by ethansaxenian** [comment]
> Regarding the "human error," we want all of the errors to be applied to the control group. If the error is randomly assigned it won't affect the consistency

Oh, I see

**Comment by ethansaxenian** [comment]
Wouldn't the human error then also be a non-random sample?

Or do we want to draw a random sample, then adjust the values of 20% of the control data _within_ that sample?

**Comment by tbyker** [comment]
ok.  tried that. new error: "please commit your changes or stash them before you switch branches. aborting"


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by tbyker** [comment]
Yes, let's do it that way.  Take a random sample.  Then, from that sample, take 20% of the control observations and multiply their earnings by 10.




**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ProfessorAmanda** [comment]
We need a more precise label than "Normal" for the selection. Otherwise I'll stay tuned for updates on this one.

**Comment by ethansaxenian** [comment]
> Yes, let's do it that way. Take a random sample. Then, from that sample, take 20% of the control observations and multiply their earnings by 10. 

Done!

> ok.  tried that. new error: "please commit your changes or stash them before you switch branches. aborting"

```
git stash
git fetch
git pull
git checkout [branch]
npm start
```

^ try that

**Comment by tbyker** [comment]
And looking ahead.  There are two possible versions of third violation:
1) some people who were randomly assigned to the control group "force their way into the treatment group."  So I could see a visualization where you pick high earning folks from the control group (highlight their points) and then show that they have shifted over to the treatment side of the graph.
2) Some of the high earning folks in the treatment group move away (maybe for better jobs in other towns) and they "leave" the population.

The idea here is that some other variable (high motivation or high skill) is now correlated with the treatment: the first is called failure to follow protocol and the second is called non-random attrition.  In the cases described, we would expect our estimate to over state the impact of job corps.

**Comment by ethansaxenian** [comment]
> We need a more precise label than "Normal" for the selection. Otherwise I'll stay tuned for updates on this one.

Agreed - any suggestions? 🤔

**Comment by tbyker** [comment]
Oh, actually the second violation (higher motivated folks atritting from the treatment group) should lead to an underestimate.

**Comment by ProfessorAmanda** [comment]
I like "OLS Assumptions Hold."

**Comment by tbyker** [comment]
tried:
git stash
git fetch
git pull
git checkout [branch]
npm start

after a while I got : "Failed to Compile" on the web browser

**Comment by ethansaxenian** [comment]
oh boy. Are you in Shannon?

**Comment by ethansaxenian** [comment]
I've adjusted the proportions for the non-random sample: now 80% of the sample is from the Job Corps group. I don't see much of a change in the simulation... what should I do?

I also added the E(u|x)=0 error type. In this one, 20% of the sampled points from the Job Corps are removed. Again, however, there is not much change in the simulation.

**Comment by ProfessorAmanda** [comment]
Well the large outliers one is working well now! We might even dial it back, lol.
[Screen Shot 2021-08-04 at 4 37 59 PM](https://user-images.githubusercontent.com/53241468/128251585-19b88fe7-05b5-42a4-aef4-fa6bf034f29d.png)

I think it may be possible that way we are imposing the "non-random sample" does not violate OLS, since we're still taking two random samples, just with different weights. I think we would need to systematically select the non-random part in a way that was correlated with the outcome variable for sure, like, say, choosing some proportion of observations from the top 50% by earnings from the job corps group.

We are learning that OLS is remarkably robust! lol 

I'm not sure about the last one (E(u|x) = 0). Is that the one where there is an omitted variable or something?

**Comment by ethansaxenian** [comment]
> And looking ahead. There are two possible versions of third violation:
> 
> 1. some people who were randomly assigned to the control group "force their way into the treatment group."  So I could see a visualization where you pick high earning folks from the control group (highlight their points) and then show that they have shifted over to the treatment side of the graph.
> 2. Some of the high earning folks in the treatment group move away (maybe for better jobs in other towns) and they "leave" the population.

The E(u|x)=0 option is number 2. of Tanya's suggestions

**Comment by ProfessorAmanda** [comment]
Right, got it, and that's very similar to my suggested "fix" for the non-random sampling idea.

**Comment by tbyker** [comment]
So from the E(u|x)=0 example, you need to specifically move out people with above average earnings for this to work.  If you randomly throw out 20% it will be harder to detect (though I think it should still be there)


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by tbyker** [comment]
Here is my original response to the non-random sample "problem" (which after thinking about it... is wrong, but I leave it here so that I can explain why): Regarding the non-random sample, since by definition, the average earnings are higher in the treatment group (we set it up that the mean was higher in that group -- we said there was a positive treatment effect), we should get a higher impact of the treatment if we oversample from that group ( I believe).  As a way to check, can you try regenerating the population with a bigger mean difference between the control and Job Corps.

Wait! don't try what I said to try ^^^ That reasoning is wrong, because the dummy variable regression just compares the means in the two groups and if we just make the sample artificially bigger for one group, but still randomly selected) the mean will still be unbiased as will the mean comparison (treat vs control).

So, here is another idea...it gets a little convoluted so probably not a great idea but I think we need something like this: Let's say that the researchers wind up sampling some group (older respondents) because they are more likely to check their email to complete the survey but the job corps program didn't work for them as well for older respondents -- then the non-random sample leads us to underestimate the overall average impact of the program.  Or, those who don't find jobs are most likely to be at home to respond to the survey, and this makes us oversample from the bottom of the treated group distribution and again we conclude the program didn't work.  The issue in both cases involves not a random oversampling, but oversampling from a specific subset of people (and essentially the problem is that the characteristic that defines over sampling is correlated with the outcome).

Do you think either of these are possible to implement?  In some ways the result is similar to selective attrition, but the story is different.

Maybe instead of the selective attrition example for E(u|x)=0 we use the "failure to follow protocol" so that we aren't essentially using the same example twice.

Happy to talk about this more if any of this is confusing!

**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
Yeah, I think this makes sense. If you can give me some numbers I'll see what I can do.

**Comment by ethansaxenian** [comment]
Just replaced selective attrition with failure to follow protocol!

**Comment by tbyker** [comment]
Non-Random Sample:

image

This example is about a mean, not a regression, which is what adds the wrinkle because we need the characteristic (less likely to answer the phone because at work) to be correlated with the treatment effect. 

Can we try this:  Do a random sample from the bottom half of the (overall) earnings distribution.  From the full pooled sample (treatment and control) find the median and take a random sample from the observations below the median.  I actually think this should give us a biased result because the treatment group was more likely to be shifted above the median by the treatment.  Maybe do this below the 30 percentile to make it even stronger.

**Comment by tbyker** [comment]
Failure to Follow Protocol:

1) take a random sample
2) take 20% of the control group sample and "apply the treatment" to them.  Meaning add a random amount to their earnings with a mean of 15.8 (with some sd).  Do this by drawing a value from the normal distribution with mean 15.8 and sd eg. 5 and add this to that 20% of control folks.
3) their dots remain on the left hand side of the figure, but they are now red.  You will probably roll your eyes at this idea: but you could make their original points light green or hallow and their bumped up points red.

**Comment by ethansaxenian** [comment]
> 3. their dots remain on the left hand side of the figure, but they are now red.  You will probably roll your eyes at this idea: but you could make their original points light green or hallow and their bumped up points red.

I personally think it would be confusing if there were more points plotted than were sampled.

**Comment by ethansaxenian** [comment]
> Can we try this: Do a random sample from the bottom half of the (overall) earnings distribution. From the full pooled sample (treatment and control) find the median and take a random sample from the observations below the median.

What if the sample size is greater than the number of points below the median? Just sample the remaining from above?

**Comment by tbyker** [comment]
Fair point.


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by tbyker** [comment]
Yeah, I was thinking about that.  let's try your suggestion.  Although since the simulation only goes to 1000 observations, we should be ok if we use below the median, right?  since the population is 2000?


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
> Yeah, I was thinking about that. let's try your suggestion. Although since the simulation only goes to 1000 observations, we should be ok if we use below the median, right? since the population is 2000? 

Yes, I think so

**Comment by ethansaxenian** [comment]
Just pushed some changes - it looks like both the non-random sampling and the failure to follow protocol are working!

I did add a new package to sample from a random normal distribution, so you will need to run `npm install`.

**Comment by tbyker** [comment]
It's working great!  Idea:  To provide variation in the sign of our bias -- can you apply the outliers to the treatment group instead of the control group?  That will give us one example with a positive rather than a negative bias.

As usual, I need to write some text....


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
Done!

**Comment by ProfessorAmanda** [comment]
Sweeeeet!

**Comment by ProfessorAmanda** [comment]
To reiterate, this is one of the coolest things we've done.

**Comment by ethansaxenian** [comment]
Ok! I am going to merge this!

**Pull request merged**
