### PR TITLE
Plot Best Fit Lines

### PR DESCRIPTION
**Pull request by ethansaxenian**
I've added two potential options in this pull request. 

The first is a separate graph at the bottom of the module that plots the best fit lines for all the samples (currently colored randomly, but of course this can be changed).

The second is plotting all the best fit lines on the sample plot. The line for the selected sample is black and the lines for the other samples are a very light gray.

We probably don't need both of these features so we may want to choose one!

### CODE REVIEW

**Comment by tbyker** [comment]
This may be a silly request (sorry), but can you send a screen shot for both? or give me the commands to try them?

**Comment by ethansaxenian** [comment]
Screen Shot 2021-07-12 at 5 46 28 PM Screen Shot 2021-07-12 at 5 46 39 PM

The commands are:

- `git checkout lines-plot`
- `git pull`
- `npm start`

**Comment by tbyker** [comment]
While I am generally a fan of color, in this case I prefer the less colorful option.




**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ProfessorAmanda** [comment]
I also prefer the grey version. And nice work!

**Review by DavidGmidd — APPROVED** [review]

**Pull request merged**
