### PR TITLE
Screen sizing update

### PR DESCRIPTION
**Pull request by ProfessorAmanda**

### CODE REVIEW

**Comment by ProfessorAmanda** [comment]
Oop!

**Comment by waynew99** [comment]
Ah, I keep introducing breaking changes! Working on fixing it......

**Comment by waynew99** [comment]
It turned out to be a next.js image loader bug. It's now fixed with a workaround.

**Comment by waynew99** [comment]
I think the logo is not loading in the deployed version. It worked fine locally... I'll make some fix and create a new PR.

**Pull request merged**
