### PR TITLE
Second Dataset for Multiple Regression

### PR DESCRIPTION
**Pull request by ethansaxenian**
I've added the gender/college/earnings dataset and allowed the user to toggle between the two datasets. We need good names for the two datasets, for now they are just labeled 1 and 2.

Check out the `second-dataset` branch - you will need to run `npm install`.

### CODE REVIEW

**Comment by tbyker** [comment]
trying to look on dell.  let's see if that works


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________
From: Ethan Saxenian ***@***.***>
Sent: Tuesday, August 3, 2021 10:26 AM
To: ProfessorAmanda/econsimulations ***@***.***>
Cc: Byker, Tanya S. ***@***.***>; Review requested ***@***.***>
Subject: [ProfessorAmanda/econsimulations] Second Dataset for Multiple Regression (#170)


I've added the gender/college/earnings dataset and allowed the user to toggle between the two datasets. We need good names for the two datasets, for now they are just labeled 1 and 2.

Check out the second-dataset branch - you will need to run npm install.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ProfessorAmanda/econsimulations/pull/170<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F170&data=04%7C01%7Ctbyker%40middlebury.edu%7C271f1f912f134244aa0308d9568aa17e%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637635975673497145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ty6FL5HyiJqjHGPpaVm%2F3c%2BazzUyBmNqQmSOt7TjFuQ%3D&reserved=0>

Commit Summary

  *   add second dataset

File Changes

  *   M package-lock.json<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F170%2Ffiles%23diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519&data=04%7C01%7Ctbyker%40middlebury.edu%7C271f1f912f134244aa0308d9568aa17e%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637635975673507139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Xle6TxKKVw6JfIeMNcPnHok%2F2zfnAYyicxNGYOSD%2BjQ%3D&reserved=0> (33)
  *   M package.json<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F170%2Ffiles%23diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519&data=04%7C01%7Ctbyker%40middlebury.edu%7C271f1f912f134244aa0308d9568aa17e%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637635975673517134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=68gKWO4T1bErK2sMkIY%2B23QjvylSzujvnec%2FGE%2FVVZc%3D&reserved=0> (1)
  *   R public/data/Class_size_Test_Scores_3vars.csv<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F170%2Ffiles%23diff-5c6814b1cd4873e7d41fa1b8597936cbeff12d077bcdb2341236300bc8297c68&data=04%7C01%7Ctbyker%40middlebury.edu%7C271f1f912f134244aa0308d9568aa17e%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637635975673517134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Zw8AHZx8cAK6cus5qnj1t%2Bsoj9VUNedPe9oAQFQ6MsA%3D&reserved=0> (0)
  *   A public/data/Small_CPS_earnings_data.csv<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F170%2Ffiles%23diff-df8ebb190aa86c58414115fc663b90edd6e1c2fade436663fdeb988472cf4d3f&data=04%7C01%7Ctbyker%40middlebury.edu%7C271f1f912f134244aa0308d9568aa17e%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637635975673527128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fTVcLqSiOJ8dcsDn5xEtOcm7t7lKmqKPzb%2FmRphAhA0%3D&reserved=0> (1001)
  *   M src/components/MultipleRegression/MultipleRegression.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F170%2Ffiles%23diff-a94eac0d1b72aa6252d44ef9698e86d16b2d229cc2da6428beb1d6567c69fe01&data=04%7C01%7Ctbyker%40middlebury.edu%7C271f1f912f134244aa0308d9568aa17e%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637635975673527128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Zfu%2Bc9T5jLzPHKDb%2FeNqxhGd0AAg%2FDo5tzvPg%2BEC4yM%3D&reserved=0> (27)
  *   M src/components/MultipleRegression/Scatter3D.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F170%2Ffiles%23diff-f388bd8e158f033527421268b441bccd8120be967bde6c1a2b559c17b302be6f&data=04%7C01%7Ctbyker%40middlebury.edu%7C271f1f912f134244aa0308d9568aa17e%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637635975673537123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8YFtCI9s%2BFUKgHcLDZ%2F8xJrDH8HadHkKTwpuxc91F08%3D&reserved=0> (67)
  *   D src/data/3d_scatter_data.json<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F170%2Ffiles%23diff-796b43a37baca2ff0b3b25c1da50d7679fa7de2374c8ec20902143701913bb73&data=04%7C01%7Ctbyker%40middlebury.edu%7C271f1f912f134244aa0308d9568aa17e%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637635975673537123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=piecYyIjzsoORg4cWOrxs3AgMzlMa2cVbsX%2FYShK8n4%3D&reserved=0> (2102)
  *   M src/lib/constants.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F170%2Ffiles%23diff-4948e93b6ff32fd5b5228f82edaceb099d7c5437eae914fe3448126e2ae075d3&data=04%7C01%7Ctbyker%40middlebury.edu%7C271f1f912f134244aa0308d9568aa17e%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637635975673547117%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Pl71UOm1LREG3y0CNwCObxxdI0UoCD97YHmcYnC1LEk%3D&reserved=0> (16)

Patch Links:

  *   https://github.com/ProfessorAmanda/econsimulations/pull/170.patch<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F170.patch&data=04%7C01%7Ctbyker%40middlebury.edu%7C271f1f912f134244aa0308d9568aa17e%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637635975673547117%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JrIzwI58EWp7XbYoa7JBAek6eYTNrObe4rlmE1qsQJ0%3D&reserved=0>
  *   https://github.com/ProfessorAmanda/econsimulations/pull/170.diff<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F170.diff&data=04%7C01%7Ctbyker%40middlebury.edu%7C271f1f912f134244aa0308d9568aa17e%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637635975673557112%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y17NpfGZWu8bM8dRtfMWTIqT6c7sv7fSle6WQ4adx9g%3D&reserved=0>

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F170&data=04%7C01%7Ctbyker%40middlebury.edu%7C271f1f912f134244aa0308d9568aa17e%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637635975673557112%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bcUncYDKx4Y3eoXh0ttmh1veT2dKt73pN6GZ2XYtw3c%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAP65VZ7PAUSVJMMGHX2WQY3T27373ANCNFSM5BO6QK5A&data=04%7C01%7Ctbyker%40middlebury.edu%7C271f1f912f134244aa0308d9568aa17e%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637635975673567106%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5NnTQO%2FA51rSPxUkeXdzcrwaJugqaTakMk%2FdBXLMY4k%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctbyker%40middlebury.edu%7C271f1f912f134244aa0308d9568aa17e%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637635975673567106%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mKlDyJVjUi5HzApPKPXWO3POrzc2fjYPpCKMDuf%2F14U%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Ctbyker%40middlebury.edu%7C271f1f912f134244aa0308d9568aa17e%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637635975673577100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NXA%2BsC0PVMjbvmT7DUpFBM95XaBqG5XMcDR%2FnhzTxXw%3D&reserved=0>.

**Comment by tbyker** [comment]
didn't work on Dell and mac is telling me " second-dataset does not match any file(s) known to git"  And actually, looking back the dell said the same thing


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
Just added the third dataset!

**Comment by tbyker** [comment]
I personally think it looks amazing!  And I think we should keep all three

I think if you add the estimated equations for each case we might be ready to deply.

Amanda, what do you think?

Small point: I don't love the word "toggle".  Any other ideas.  Is it possible for the button so say "Show best fit ..." and then once it is pushed it switches to saying "Hide best fit..." and vice versa?


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by tbyker** [comment]
Another super small point it should be "Test Scores" with an "s" rather than "Test Score"  because it is average test scores in a district not an individual's test score.


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
Just added the plot 'title'

**Comment by ethansaxenian** [comment]
@tbyker we still need menu text and intro text if you have time to write those.

**Comment by tbyker** [comment]
Ok.  Will work on text for menu and intro.  May happen later today.

Also, can the left_hand side variable have a hat in the equation?  and can each variable have an i subscript?  If hat is not possible, can you add a "+ u) to the end of the equation in all cases (preferably a u_i)


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
> Also, can the left_hand side variable have a hat in the equation?  and can each variable have an i subscript?  If hat is not possible, can you add a "+ u) to the end of the equation in all cases (preferably a u_i)

Unfortunately, I don't think the hat is possible. And the best I can do for subscripts is simply `u_i`.

**Comment by ethansaxenian** [comment]
Actually, I was able to add the subscript i's, and the change is now pushed to the branch.

**Comment by ProfessorAmanda** [comment]
I think it looks incredible! Small comment: on the CPS Earnings Data, Gender vs. College, is there any way to show the density of dots in each corner? Like a darker color for more dots? Don't worry if that's not possible or looks confusing.

**Comment by ethansaxenian** [comment]
> I think it looks incredible! Small comment: on the CPS Earnings Data, Gender vs. College, is there any way to show the density of dots in each corner? Like a darker color for more dots? Don't worry if that's not possible or looks confusing.

I don't think this is possible unfortunately.

**Comment by ethansaxenian** [comment]
Any more changes for this?

**Comment by ProfessorAmanda** [comment]
Looks good to me! A small change I would suggest is, if we're going to display the regression models, we should rename the variables to something formal/intuitive rather than using abbreviated forms. I might suggest:

TestScore_i = ...StudentTeacherRatio....PercentEngLearners
LnEarnings_i = YearsofEd...Gender

The one with earnings, college, and gender is fine.

**Comment by ethansaxenian** [comment]
Done! I'm gonna merge this!

**Pull request merged**
