### PR TITLE
Scrolling sim

### PR DESCRIPTION
**Pull request by ethansaxenian**
Tanya and I had talked last week briefly about the Law of Large Numbers simulation adjusting its axes as the sample size gets larger and larger. I've implemented that here. I removed the tooltips as they didn't work well with the plot, additionally I didn't really think they were necessary.

Let me know if this is something we should keep!

```
git checkout scrolling-sim
git pull
npm start
```

### CODE REVIEW

**Comment by tbyker** [comment]
Do I need to go to a specific branch?

I got to the econsimulations directory on my desk top and then typed your suggested command and got:

error: pathspec 'scrolling-sim' did not match any file(s) known to git


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________
From: Ethan Saxenian ***@***.***>
Sent: Thursday, July 15, 2021 10:22 AM
To: ProfessorAmanda/econsimulations ***@***.***>
Cc: Byker, Tanya S. ***@***.***>; Review requested ***@***.***>
Subject: [ProfessorAmanda/econsimulations] Scrolling sim (#134)


Tanya and I had talked last week briefly about the Law of Large Numbers simulation adjusting its axes as the sample size gets larger and larger. I've implemented that here. I removed the tooltips as they didn't work well with the plot, additionally I didn't really think they were necessary.

Let me know if this is something we should keep!

git checkout scrolling-sim
git pull
npm start


________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ProfessorAmanda/econsimulations/pull/134<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F134&data=04%7C01%7Ctbyker%40middlebury.edu%7Cb4dc37c7b7c14d2bc7f108d9479c0987%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637619557762517207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BcIsI93LUQEpSCyoLDMFG2ZOnqW%2BOFEnvMt%2FMkH8a2M%3D&reserved=0>

Commit Summary

  *   fix lint
  *   adjust test'
  *   adjust test
  *   scrolling sim
  *   Merge branch 'master' of https://github.com/ProfessorAmanda/econsimulations into lln-sim
  *   Merge branch 'master' of https://github.com/ProfessorAmanda/econsimulations into lln-sim
  *   Merge branch 'master' of https://github.com/ProfessorAmanda/econsimulations into lln-sim
  *   stop at 1000

File Changes

  *   R src/__tests__/SelectorButtonGroup.test.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F134%2Ffiles%23diff-b0e789a32d2bc3126ebecab5920fd877ad15c9f58bb035b4e7e17df6dc32b700&data=04%7C01%7Ctbyker%40middlebury.edu%7Cb4dc37c7b7c14d2bc7f108d9479c0987%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637619557762517207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PUPa4o%2FqwTOKySnsCBYZyera46uKLVQqDr9OwV%2BcN54%3D&reserved=0> (8)
  *   M src/components/ChartContainer.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F134%2Ffiles%23diff-c61f20cc00bfdd87f5a7fdeaf5846527a8f6d44bf13a90197863e4c9f44251cc&data=04%7C01%7Ctbyker%40middlebury.edu%7Cb4dc37c7b7c14d2bc7f108d9479c0987%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637619557762527210%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=R14vfajslcm82SMMSFEoFuMrcLag%2FDwVD5pZeRcs0gA%3D&reserved=0> (2)
  *   M src/components/LawOfLargeNumbers/SimulateSamples.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F134%2Ffiles%23diff-960ce4f29972249c45d1f874dd0d1bc2cdde5e38510c5f358e747c2b46c67a5f&data=04%7C01%7Ctbyker%40middlebury.edu%7Cb4dc37c7b7c14d2bc7f108d9479c0987%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637619557762537219%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=z8zssznxWfevc1S8w%2FmR9tVJcWwHjgEg8ul0tp76kuc%3D&reserved=0> (15)

Patch Links:

  *   https://github.com/ProfessorAmanda/econsimulations/pull/134.patch<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F134.patch&data=04%7C01%7Ctbyker%40middlebury.edu%7Cb4dc37c7b7c14d2bc7f108d9479c0987%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637619557762537219%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UOeD00g3j24HLs2yhLMwLnTYs6wrCamoBUGGjgK%2FxJk%3D&reserved=0>
  *   https://github.com/ProfessorAmanda/econsimulations/pull/134.diff<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F134.diff&data=04%7C01%7Ctbyker%40middlebury.edu%7Cb4dc37c7b7c14d2bc7f108d9479c0987%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637619557762547199%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aL57WSHU0JObI9ZjMWSX1SfhUBCNmFrEsGGXHvF%2Fsfs%3D&reserved=0>

**Comment by ethansaxenian** [comment]
> Do I need to go to a specific branch? I got to the econsimulations directory on my desk top and then typed your suggested command and got: error: pathspec 'scrolling-sim' did not match any file(s) known to git 

Try running `git fetch` first

**Comment by tbyker** [comment]
That worked!

I personally like it a LOT.  What do you think, Amanda?  though it is very slow.  I there any way to speed it up after 500 obs or so?

I would personally also prefer that the simulation start with a button rather than automatically.  Thoughts?


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ProfessorAmanda** [comment]
I agree with Tanya on all points! Really love the idea and how it is working already, but those tweaks TB has suggested (speed up after 500, having some kind of "start" button) would be great.

**Comment by tbyker** [comment]
Yeah, I don't know if "variable" speed is actually a possibility.  But my idea scenario is that once you push the "simulate" button we have it start off slow so user gets a sense of what is going on and then pick up speed once observations get into the mid hundreds.  But I suspect what is slowing things down is the sample size lol.  Another possibility (but not worth a huge investment in time) is to not sample every integer sample size over, say, 200.  Like rather than 300, 301, 302 etc, we go to 300, 325, 350 etc.  I don't think you would see the gaps on the graph.

T


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
> I would personally also prefer that the simulation start with a button rather than automatically.  Thoughts?

I also think this is a good idea

> Yeah, I don't know if "variable" speed is actually a possibility.

The way to speed up the simulation would be to plot multiple points at once, which is certainly doable, but would make it seem more choppy

> But I suspect what is slowing things down is the sample size lol.

I don't think it is actually slowing down, rather it just looks slower!

**Comment by tbyker** [comment]
How choppy?  And could you add it after 300?  If not, let's just leave it.

Super cool though!  I am very happy with the changing axis!


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
> How choppy?  And could you add it after 300?  If not, let's just leave it.

I just pushed some changes, it now increases to 2x speed after 300, and is actually not very choppy at all! Let me know what you think!

(remember to `git pull` to get the most recent changes)

**Comment by tbyker** [comment]
Amazing!  Please don't kill me:  Can the speed up Start it at 200 and maybe do 2.5 speed or maybe ramp to 3X at 400.  I just don't want the user to lose interest.  Also when the simulation was over the plotted means disappeared.

[cid:a226e389-14e2-4f1e-a104-893b48dbd2ce]


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
I just increased the overall speed by 2x, although it might be too fast now... thoughts?

**Comment by ethansaxenian** [comment]
Now it doubles in speed at 300, and doubles again at 600.

**Pull request merged**
