### PR TITLE
Multiple Regression Updates

### LINKED ISSUE #144: 3D regression updates
The `3d-regression` branch now has buttons to toggle the best fit line/plane. I've also labeled the axes and styled the markers a bit to make them more distinct.

A few things we still need:
- A better name for the module?
- A graph title
- Better labels for the buttons

### LINKED ISSUE #164: Add buttons with text that change the graph view
What we said, with "radio" buttons: 
Display:

-  Test Scores vs Student Teacher ratio and Percent of English Learners
- Test Scores vs. Student Teacher ratio
- Test Scores vs. Percent of English Learners

Best Fit:
Show/Hide

### PR DESCRIPTION
**Pull request by ethansaxenian**
Swapped the X and Y axes and added the radio buttons instead of using the buttons in the modebar.

Would this be ready for deployment?

closes #144, closes #164

### CODE REVIEW

**Comment by ethansaxenian** [comment]
Oh, we need the intro and menu text for the module first!

**Review by ProfessorAmanda — APPROVED** [review]
I like it! (Yes, needs some text before deployment)

**Comment by ethansaxenian** [comment]
Shall I merge this to master or wait for menu text?

**Comment by ProfessorAmanda** [comment]
Go ahead and merge to master.

**Pull request merged**
