### PR TITLE
Finalize ols estimators module

### LINKED ISSUE #151: Finalizing the module
Binary example:
1) can you tell me which table you were looking at in the Job Corps report to get the means so that I can write a little text?
2) Can you put the information about the estimated line above the sample plot as we do in the continuous example?  (like earnings_hat = beta_0_hat .... in the beta form and also with the estimate for the relevant sample at hand?
3) When switching from continuous to binary, can you make sure the "standardize" button gets unclicked so that someone starts out in the unstandardized mode.  If you were in standardize in continuous and switch to binary the standardize button remains clicked.  

Working on text for the menu page and for the intro

### PR DESCRIPTION
**Pull request by ethansaxenian**
Added changes from #151 and added the intro and menu texts. Anything else we need?

closes #151

### CODE REVIEW

**Comment by tbyker** [comment]
I think ultimately, I want to put in a little more text about what is going on in the binary job corps example and maybe think about the means, but I think we can deploy and tinker more later?  Amanda?  Hopping on a call.  will be back later


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________
From: Ethan Saxenian ***@***.***>
Sent: Friday, July 30, 2021 1:56 PM
To: ProfessorAmanda/econsimulations ***@***.***>
Cc: Byker, Tanya S. ***@***.***>; Review requested ***@***.***>
Subject: [ProfessorAmanda/econsimulations] Finalize ols estimators module (#152)


Added changes from #151<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fissues%2F151&data=04%7C01%7Ctbyker%40middlebury.edu%7C3af2c393b292447f537308d95383592f%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637632645865743971%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PZRwTu%2BGnRJgrZuz8lA9tmMaE7ByhuQ3iZgYuBxqzDs%3D&reserved=0> and added the intro and menu texts. Anything else we need?

closes #151<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fissues%2F151&data=04%7C01%7Ctbyker%40middlebury.edu%7C3af2c393b292447f537308d95383592f%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637632645865743971%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PZRwTu%2BGnRJgrZuz8lA9tmMaE7ByhuQ3iZgYuBxqzDs%3D&reserved=0>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ProfessorAmanda/econsimulations/pull/152<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F152&data=04%7C01%7Ctbyker%40middlebury.edu%7C3af2c393b292447f537308d95383592f%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637632645865753971%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FUUgCep%2FbaIpSq4Nb5QwheJ1Gczb4LXV5xjT2AflzqA%3D&reserved=0>

Commit Summary

  *   display math
  *   uncheck on pop switch
  *   add texts

File Changes

  *   M src/components/SampleDistributionOLSEstimators/InterceptDistributionPlot.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F152%2Ffiles%23diff-8f3954960f44d6231cab268c3a978485525fa2418a865c1c4327b9c128fab0bb&data=04%7C01%7Ctbyker%40middlebury.edu%7C3af2c393b292447f537308d95383592f%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637632645865753971%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XV468ueESEkjtSApXxuYxWC2tAq9sRnXx8gd2qenTak%3D&reserved=0> (7)
  *   M src/components/SampleDistributionOLSEstimators/PopulationAndSampleCharts.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F152%2Ffiles%23diff-a2cc658e111285be57713457a500a8ad1aab8422fc250a2aeb93c1e29b7c5ca2&data=04%7C01%7Ctbyker%40middlebury.edu%7C3af2c393b292447f537308d95383592f%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637632645865763960%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YRt9uEWvM8e3v%2B7xrHFLop1JemQwajA%2FDLezBvQmw70%3D&reserved=0> (15)
  *   M src/components/SampleDistributionOLSEstimators/SampleDistributionOLSEstimatorsContainer.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F152%2Ffiles%23diff-3883d3fdb79602f5e566693b79d5d19fd49bd25c21babb520e7b81d0668bd603&data=04%7C01%7Ctbyker%40middlebury.edu%7C3af2c393b292447f537308d95383592f%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637632645865773954%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2S6wdXnY6eqLYm%2FWje1h9vI7hEi3DJVbmR4NwMAq1Qw%3D&reserved=0> (6)
  *   M src/components/SampleDistributionOLSEstimators/SlopeDistributionPlot.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F152%2Ffiles%23diff-7b526b3ec94608a94c7fbc0f8113bcdee3f5596c0e54c2d132bf163faf14d90b&data=04%7C01%7Ctbyker%40middlebury.edu%7C3af2c393b292447f537308d95383592f%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637632645865773954%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3knUCcQrezfx3vM2RnLn4djd7XZZxwbUmHsfVermKyE%3D&reserved=0> (7)
  *   M src/lib/constants.js<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F152%2Ffiles%23diff-4948e93b6ff32fd5b5228f82edaceb099d7c5437eae914fe3448126e2ae075d3&data=04%7C01%7Ctbyker%40middlebury.edu%7C3af2c393b292447f537308d95383592f%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637632645865783948%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kIskuinI3BOHQOfqJ81Us7%2BsE0yeo%2BE2YIcBB0x3UM4%3D&reserved=0> (4)

Patch Links:

  *   https://github.com/ProfessorAmanda/econsimulations/pull/152.patch<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F152.patch&data=04%7C01%7Ctbyker%40middlebury.edu%7C3af2c393b292447f537308d95383592f%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637632645865783948%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vBxUgAnwi3vWZRGB7mkJzs4AuOkBgYW5Og%2FFpngwBtU%3D&reserved=0>
  *   https://github.com/ProfessorAmanda/econsimulations/pull/152.diff<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fpull%2F152.diff&data=04%7C01%7Ctbyker%40middlebury.edu%7C3af2c393b292447f537308d95383592f%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637632645865793944%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5Sy5AZP29Unrui0EeIxvQfT0BfYFbfLFYEsWDswRzzA%3D&reserved=0>

**Comment by ProfessorAmanda** [comment]
Okay don't roll your eyes so far back into your head that you hurt yourselves but the menu text should have "sampling distributions" with an "s" for subject-verb agreement.

**Comment by tbyker** [comment]
lol.  I must have missed that!  But again, I don't see it on the site


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ProfessorAmanda** [comment]
You need to be on the branch called "finalize-ols" to see it

**Pull request merged**
