### PR TITLE
Click to Add New Points

### PR DESCRIPTION
**Pull request by ethansaxenian**
Added the ability for the user to click to add new points on the Least Squares plot

### CODE REVIEW

**Comment by ProfessorAmanda** [comment]
I'm absolutely stunned. It works. 
To deploy, we'll need (a) some kind of text conveying to the reader that adding points is an options, and (d) delete "Chart Title."

**Comment by ethansaxenian** [comment]
Just added a caption and removed the chart title

**Comment by ethansaxenian** [comment]
Is this ready to be merged?

**Comment by tbyker** [comment]
how can I look at this?  I don't seem to be able to get things on the master branch to work on my Dell.  even after npm install etc.


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
Unfortunately, because the Multiple Regression module is on the master branch, I don't think it will work on the Dell

**Comment by ethansaxenian** [comment]
Just pushed a commit that allows the user to enable/disable this feature!

**Comment by ProfessorAmanda** [comment]
I'm on the click-points branch, and I don't see a way to enable/disable adding points. (Just can't add points).

**Comment by ethansaxenian** [comment]
Did you `git pull`?

**Comment by ProfessorAmanda** [comment]
Yes. I did get an error about needing to stash my package.json file before I pulled? But I pulled anyway. Ha.

Amanda G. Gregg
Assistant Professor of Economics, Middlebury College
Join My Personal Zoom Room<https://middlebury.zoom.us/my/agregg?pwd=OWlGMmZMSWJaUkowRG5DUWJtRm9CQT09> (Password: EconHist)
Office: Farrell House 101
Office Phone: (802) 443 - 3419
Pronouns: she/her/hers

________________________________

**Comment by ProfessorAmanda** [comment]
Oh, I see. I wasn't able to switch branches because of that error. Here's what I see: 
Screen Shot 2021-08-03 at 4 01 40 PM

**Comment by ethansaxenian** [comment]
Ah, run 
```
git stash
git pull
```

**Comment by ProfessorAmanda** [comment]
Thanks, that worked, and I love it!

**Comment by ethansaxenian** [comment]
Is this ready to be merged?

**Comment by ProfessorAmanda** [comment]
Yeah I say merge it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
