### PR TITLE
plot distribution of f-statistic

### LINKED ISSUE #193: Perhaps one solution to the desire for something visual is to simulate the distribution of the F statistic. For the given population parameters, could we, say, take 1000 (or whatever) samples as specified by the user, and plot the resulting F statistics as usual?

### PR DESCRIPTION
**Pull request by ethansaxenian**
closes #193

### CODE REVIEW

**Comment by ProfessorAmanda** [comment]
Neato! It has the right shape for sure. I'm struck that the lower bound for the F values in the replication tends to be the F value shown in the test. That might be right, just by chance, but seems unlikely given the number of attempts I tried. Let's check to make sure a) that the F-statistic is being calculated properly (should only depend on sample numbers) and that b) a new sample is drawn for each replication.

**Comment by ProfessorAmanda** [comment]
I'll also come up with some text to describe what is being plotted. (It's *not* a type 1 error simulation).

**Comment by ethansaxenian** [comment]
A new sample is definitely being drawn for each population. As to the correctness of the F-Statistic, this is the pseudocode I'm using:

```
overallSampleMean = mean(all sample observations)
SSTR = sum(for each population p, size(p) * (mean(p) - overallSampleMean)^2)
MSTR = SSTR / (number of populations - 1)
SSE = sum(for each population p, (size(p) - 1) * standardDev(p)^2)
MSE = SSE / (sum(size of each population) - number of populations)
F = MSTR / MSE
```

Let me know if this makes sense/is correct

**Comment by ProfessorAmanda** [comment]
Yes, that's correct. 

I think that, seeing this, I've realized that what I really want is a Type I error simulation. So, scrap the replication for now, but keep the code, as you will need it to simulate Type I error. I'm going to make a separate issue to outline how to do it.

**Pull request closed without merging**
