### PR TITLE
Menu changes

### PR DESCRIPTION
**Pull request by ethansaxenian**
I decided to experiment a little with the menu. Let me know what you think!

P.S. I have no attachment to this so if you don't like it, please tell me and I can scrap the idea.

### CODE REVIEW

**Comment by ProfessorAmanda** [comment]
I rather like it!

**Review by ProfessorAmanda — APPROVED** [review]

**Comment by ethansaxenian** [comment]
I've now made the module titles larger and bold and a deep blue (not sure I like this, however)

**Comment by ProfessorAmanda** [comment]
I think I liked the previous version better?

**Comment by ethansaxenian** [comment]
I think I did too.

**Comment by tbyker** [comment]
Ok fine. Lol. I can’t see as sitting in waiting room. Can they at least just be bold

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ethansaxenian** [comment]
> Ok fine. Lol. I can’t see as sitting in waiting room. Can they at least just be bold Get Outlook for iOS

Done.

**Comment by ProfessorAmanda** [comment]
What do you think, Tanya? I trust your aesthetic sense more than my own! I think this is an improvement, since the bold black does not clash the way the blue did.

Screen Shot 2021-07-30 at 4 35 01 PM

**Comment by tbyker** [comment]
Looks good!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
