### PR TITLE
Simulate type 1 error

### PR DESCRIPTION
**Pull request by ethansaxenian**
Populations can now be generated and f-stats are plotted.

How do we want to represent rejecting/accepting? Similar to hypothesis testing where the points are red/green? 

What information should we include in the tooltip for each point? I'm thinking f-stat, pval, reject/accept at least.

Still need to add summary text.

### CODE REVIEW

**Comment by ProfessorAmanda** [comment]
Looks so good! I'll have to think about whether there are any minor changes, but I'm really happy with this already. To answer your questions:
1. Yes, red/green dots is perfect.
2. Those pieces of info for the tooltip would be great. 
3.  I'll keep posted for the summary text addition.

**Comment by ethansaxenian** [comment]
The points are now color coded accordingly!

**Comment by ethansaxenian** [comment]
...and summary text is now added

**Comment by ProfessorAmanda** [comment]
Check the calculation of those p-values. All the red dots should be bunched up at the right tail. Also, given the same sample sizes and the same number of groups, the same F statistics should yield the same p-values, which they currently do not.

**Comment by ProfessorAmanda** [comment]
I checked the math for the F-stats above. Actually I think the p-values are correct but the SSTR and SSE are somehow calculated incorrectly. Check parentheses in your formulas.

**Comment by ethansaxenian** [comment]
> Check the calculation of those p-values. All the red dots should be bunched up at the right tail. Also, given the same sample sizes and the same number of groups, the same F statistics should yield the same p-values, which they currently do not.

The p-values are calculated using the jStat function... I hope this isn't the problem.

Actually, the jStat function takes a list of arrays (the samples?) which will be different in each replication.

**Comment by ProfessorAmanda** [comment]
I found the mistake in your F formula. You were using population sizes instead of sample sizes.

**Comment by ethansaxenian** [comment]
> jStat.anovaftest( array1, array2, ...., arrayn )
Returns the p-value of the f-statistic from the ANOVA test on the arrays.

**Comment by ethansaxenian** [comment]
> I found the mistake in your F formula. You were using population sizes instead of sample sizes.

In which calculation? Should it be all of them?

**Comment by ProfessorAmanda** [comment]
Everywhere you calculate an SSTR or an SSE. The numerators have the *sample sizes*, not the population sizes.

**Comment by ProfessorAmanda** [comment]
SSTR = sum(over populations) sample size * (sample mean - overall mean)^2

SSE = sum(over populations) (sample size - 1) * (sample std dev)^2

**Comment by ProfessorAmanda** [comment]
(Where sample size = sample size drawn from group k)

**Comment by ethansaxenian** [comment]
Ok, should be fixed. The problem now is that there are a lot of f-stats = 0, which throws off the scale of the plot.

**Comment by ProfessorAmanda** [comment]
Good! At least it's working in the sense of all red dots to the right. Don't forget to fix the F stats in the top part of the module as well. 

As far as the scaling goes, there shouldn't be any F stats that are exactly 0 (that's only possible if the sample means are all exactly equal), so you could try to fiddle with how the F values are rounded. It's not great for them to show up as zero in the tooltips.

**Comment by ethansaxenian** [comment]
> Good! At least it's working in the sense of all red dots to the right. Don't forget to fix the F stats in the top part of the module as well.

Thanks for the reminder!

> As far as the scaling goes, there shouldn't be any F stats that are exactly 0 (that's only possible if the sample means are all exactly equal), so you could try to fiddle with how the F values are rounded. It's not great for them to show up as zero in the tooltips.

It looks like there are always some points that end up 0, even with no rounding. Not sure what to do here.

**Comment by ProfessorAmanda** [comment]
> It looks like there are always some points that end up 0, even with no rounding. Not sure what to do here.

Interesting. I mean, it's possible, just unlikely. If you could print for yourself a report of the sample means and the overall means that are generated by the replications, you can check to make sure the math is right. F=0 if and only if all sample means are equal.

**Comment by ethansaxenian** [comment]
> Interesting. I mean, it's possible, just unlikely. If you could print for yourself a report of the sample means and the overall means that are generated by the replications, you can check to make sure the math is right. F=0 if and only if all sample means are equal.

Actually, this makes a lot of sense. I've only been testing with 2 populations (the default), and the population observations are all rounded to the nearest whole number, so it does happen that sample means are equal.

**Comment by ProfessorAmanda** [comment]
> and the population observations are all rounded to the nearest whole number

I get why it makes sense to round to the nearest whole number for the pictures, but is it possible to use unrounded numbers to calculate the SSTR, SSE, and F stats? Or numbers rounded to the nearest .1 or .01?

**Comment by ProfessorAmanda** [comment]
(We are a little bit splitting hairs, since it only seems to really matter for 2 populations)

**Comment by ethansaxenian** [comment]
> (We are a little bit splitting hairs, since it only seems to really matter for 2 populations)

This is true. Regardless, I've just pushed a change that rounds the populations to the nearest 0.1 (for the pictures too) and it solves the problem, although the pictures look a bit weirder. Let me know what you think.

**Comment by ProfessorAmanda** [comment]
I like it! Pictures look okay to me.

**Comment by ethansaxenian** [comment]
> I like it! Pictures look okay to me.

I actually like it a lot less. I say we either live with it as is or, since it only matters with 2 populations, limit to a minimum of 3

**Comment by ProfessorAmanda** [comment]
Maybe I should ask: which pictures look odd to you? The samples, maybe?

**Comment by ProfessorAmanda** [comment]
Found another math error in the portion above, which may apply to the type 1 simulation as well. 

Check the calculation of the MSE. I did one by hand, and it was off by a factor of about ten. The MSE should be the SSE / (total sample size - number of groups), i.e. it should be the SSE / the degrees of freedom in the "due to error" row.

**Comment by ProfessorAmanda** [comment]
Looks killer! See you in ten.

**Comment by ProfessorAmanda** [comment]
Add to the distribution title, in parentheses, (df_num = [number of groups - 1], df_den = [total sample size - num of groups])

**Comment by ProfessorAmanda** [comment]
Looks good! Small mistake: df_num = number of groups - 1 (i.e. don't forget to subtract 1)

**Review by ProfessorAmanda — APPROVED** [review]
Merge it!

**Pull request merged**
