### PR TITLE
show regression equation

### PR DESCRIPTION
**Pull request by waynew99**
Screen Shot 2022-06-06 at 13 39 01

Resolves issue #280 

[Feature]
I've added the presentation of regression equation to the right of the chart. It adapts to the newest regression line when new examples are generated. The equation for Corrected Regression is shown / hidden in sync with the regression line on the chart.

[Questions]
1. Is the expression format "f(x)=2.79x+56.89" the correct one for the regression equation in this context?
2. Currently, on every re-generation of examples, the Corrected Regression line is hidden by default. Is it a feature wanted? Do we want to keep it that way?

Please let me know if there's any problem running the branch "OVBequations" locally, or any changes you would like me to make :)

### CODE REVIEW

**Comment by ProfessorAmanda** [comment]
Great first pull request, Wayne! :)

1. I want to get Tanya's opinion on how the equations look now, particularly about whether we should we use y and x, or the names of the variables.
2. Yes, we want the Corrected Regression line to be hidden by default, so that each time we generate new data, the user has to click the "reveal" button and experience an a-ha moment.

**Comment by tbyker** [comment]
Hi Wayne,
This is looking great.  In terms of how the equation should appear, can you take a look at the multiple regression module (click show best fit line/plane).  We do want the variable names to appear in the equation (instead of "x" and f(x).  For the "corrected" line, we should also include the coefficient on Sleep.  I am not sure how that is getting reported in the regression output in javascript, but it should be there somewhere.  Happy to hop on zoom and explain any of this if needed.

Best,

Tanya


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by waynew99** [comment]
Hi Professors,

Thanks for the explanations!
Just to confirm, we want
`TestScore = beta0 + beta1 * StudyHours + delta * SleepHours + epsilon`

My understanding is that the user sets `beta1` and `delta`, and we supply `beta0` and `epsilon`. 
- For `beta1` and `delta`, we put the values that the user defines.
- For `beta0`, currently, it is hard coded as 40. Should we put 40 or beta0 in the equation?
- For `epsilon`, I see it coming from a normal distribution. What should we put here in place of epsilon?

Thanks,
Wayne

**Comment by waynew99** [comment]
Thanks! It does make sense.

I've also moved it to the bottom of the graph due to the length of the equation (it's probably not ideal to split one equation into two lines).

Please let me know if I didn't understand correctly!

Best,
Wayne

Screen Shot 2022-06-06 at 16 08 28

**Comment by tbyker** [comment]
Hi Wayne,
The two equations should be different.  For the example listed:

The naive regression: it looks like the estimated intercept is around 65, and should have an estimated beta_1 much closer to zero.  Also, in the naive regression, the delta should not appear as technically, sleep is in the error term in that initial regression.

The corrected regression line looks correct.

Does this make sense?

Best,

Prof. Byker


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by waynew99** [comment]
Hi Professor Byker,

Sorry for the misinterpretation! I should have made sure I understood it correctly before attempting those modifications. Does this look right?

Best,
Wayne

Screen Shot 2022-06-06 at 16 22 54

**Comment by tbyker** [comment]
Great!  And the corrected line should only appear once the user has clicked the "show corrected line" button.

Thanks!

Tanya


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Pull request merged**
