### PR TITLE
p-value for t-test

### LINKED ISSUE #138: Incorrect calculation of p-value for t-test?
Currently we are calculating the p-value for a z-test according to these rules:
IMG_2578

However, no such calculations are happening for a t-test.

### PR DESCRIPTION
**Pull request by ethansaxenian**
I've attempted to correct the calculation of the p-value for the t-test case. I've also simplified the code a bit - we are doing the test stat and p-value calculations twice in different components so I've modularized these calculations and put them into `stats-utils.js`.

I am, however, worried that I broke something in the process. It might be a good idea to run a few tests when we meet tomorrow before we merge this pull request.

closes #138

### CODE REVIEW

**Comment by ProfessorAmanda** [comment]
The test for single samples looks like it's working correctly for all varieties of hypotheses. Should the simulation be working correctly on this branch? In two-sided tests, with t, the null hypothesis was never rejected in the simulation (all green dots). It is working fine for Z.

**Comment by ethansaxenian** [comment]
> Should the simulation be working correctly on this branch? In two-sided tests, with t, the null hypothesis was never rejected in the simulation (all green dots). It is working fine for Z.

The simulation should be working correctly - I will look into that.

**Comment by ethansaxenian** [comment]
Fixed! There was a bug where we were using the direction of the hypothesis in a function but not actually passing that parameter into the function.

**Comment by ProfessorAmanda** [comment]
Sweet! Lookin good. I'm merging it.

**Comment by ethansaxenian** [comment]
I think we might be able to deploy Hypothesis testing! What do we think?

**Comment by ProfessorAmanda** [comment]
Yeah let's aim to deploy tomorrow. I'll try to spend some time this evening checking every single permutation of it to make sure everything is working.

Amanda G. Gregg
Assistant Professor of Economics, Middlebury College
Join My Personal Zoom Room<https://middlebury.zoom.us/my/agregg?pwd=OWlGMmZMSWJaUkowRG5DUWJtRm9CQT09> (Password: EconHist)
Office: Farrell House 101
Office Phone: (802) 443 - 3419
Pronouns: she/her/hers

________________________________

**Pull request merged**
